quake_parser/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  root to: 'home#index'

  get 'home/index'
  get 'ranking/players'

  resources :log_files, only: [:new, :index, :create, :show] do
    get :kills_report, on: :member
    get :kills_report_by_cause, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

quake_parser/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quake_parser/app/models/kill.rb
class Kill < ApplicationRecord
  belongs_to :match

  scope :only_players, ->{ where.not(player: '<world>') }
  
  scope :world_kills, ->{ where(player: '<world>') }

  def self.ranked_players
    raw_score = only_players.group(:player).count
    
    world_kills.group(:victim).count.each do |player, penalty|
      raw_score[player] = 0 if raw_score[player].nil?

      raw_score[player] -= penalty
    end

    Hash[raw_score.sort_by{ |_, v| -v }]
  end
end

quake_parser/app/models/log_file.rb
class LogFile < ApplicationRecord
  has_one_attached :quake_log
  has_many :matches

  validates :name, presence: true
  validates :quake_log, presence: true

  def finish!
    update(status: :finished)
  end
end

quake_parser/app/models/match.rb
class Match < ApplicationRecord
  has_many :kills
  belongs_to :log_file

  def kills_report 
    {
      name => {
        total_kills: total_kills,
        players: list_players,
        kills: net_players_kills
      }
    }
  end

  def kills_report_by_cause
    {
      name => kills_by_cause
    }
  end

  private 
  def list_players
    kills.only_players.distinct.pluck(:player).sort
  end

  def kills_by_players
    kills.only_players.group(:player).count
  end

  def kills_by_cause
    kills.group(:cause).count
  end

  def kills_by_world
    kills.world_kills.group(:victim).count
  end

  def net_players_kills
    raw_score = kills_by_players
    kills_by_world.each do |player, penalty|
      raw_score[player] = 0 if raw_score[player].nil?

      raw_score[player] -= penalty
    end

    raw_score
  end

  def total_kills
    kills.count
  end
end

quake_parser/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

quake_parser/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

quake_parser/app/controllers/log_files_controller.rb
class LogFilesController < ApplicationController
  def index
    @log_files = LogFile.all
  end

  def show
    @log_file = LogFile.find(params[:id])
  end

  def new 
    @log_file = LogFile.new
  end

  def create 
    @log_file = LogFile.new(permitted_params)

    respond_to do |format|
      if @log_file.valid? && @log_file.save
        FileParserWorker.perform_async(@log_file.id)
        format.html { redirect_to @log_file, notice: "Log File was successfully created." }
      else  
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def kills_report
    log_file = LogFile.find(params[:id])
    report = log_file.matches.map(&:kills_report)

    render json: report
  end

  def kills_report_by_cause
    log_file = LogFile.find(params[:id])
    report = log_file.matches.map(&:kills_report_by_cause)

    render json: report
  end

  private
  def permitted_params
    params.require(:log_file).permit(:name, :quake_log)
  end
end

quake_parser/app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  def players
    render json: Kill.ranked_players
  end
end

quake_parser/app/helpers/application_helper.rb
module ApplicationHelper
end

quake_parser/app/helpers/home_helper.rb
module HomeHelper
end

quake_parser/app/helpers/send_log_helper.rb
module SendLogHelper
end

quake_parser/app/views/home/index.html.erb
<h1>Quake log test</h1>
<p><%= link_to 'See log files', log_files_path %></p>
<p><%= link_to 'Download current ranking', ranking_players_path, format: :json, target: "_blank" %></p>

quake_parser/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuakeParser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

quake_parser/app/views/log_files/index.html.erb
<h1>Files</h1>
<p><%= link_to 'Send new log file', new_log_file_path %></p>
<p><%= link_to 'Home', root_path %></p>
<br />
<h2>All log files<h2>
<table class="table">
<thead>
  <tr>
    <th>File name</th>
    <th>Status</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% @log_files.each do |log_file| %>
    <tr>
      <td><%= link_to log_file.name, log_file_path(log_file) %></td>
      <td><%= log_file.status %></td>
    </tr>
  <% end %>
</tbody>
</table>

quake_parser/app/views/log_files/new.html.erb
<%= form_with model: @log_file do |f| %>
  <% if @log_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log_file.errors.count, "error") %> prohibited this log file from being saved:</h2>

      <ul>
        <% @log_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :quake_log %>
    <%= f.file_field :quake_log, multiple: false %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

quake_parser/app/views/log_files/show.html.erb
File name: <%= @log_file.name %>
<br />
<% if @log_file.status == 'finished' %>
<%= link_to 'Download kills report', kills_report_log_file_path, format: :json, target: "_blank" %>
<br />
<%= link_to 'Download kills by cause', kills_report_by_cause_log_file_path, format: :json, target: "_blank" %>
<% else %>
Processing report
<% end %>

<br />
<br />
<%= link_to 'Upload new log', new_log_file_path %> | <%= link_to 'Back to log files', log_files_path %> | <%= link_to 'Home', root_path %>